org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.20.1
forge_version=47.2.0
mod_version=1.0.0
mod_group_id=pl.daniel.herbsmoking
mod_id=herbsmoking
mod_name=Herb Smoking Mod
mod_authors=Daniel
mod_description=Trzy odmiany ziół (Indica, Sativa, CBD), sadzonki, bongo, fajki - wersja Forge 1.20.1